---
services:
  db:
    image: sandeep1405/pythonapp:dbimage
    ports:
      - "3306:3306"
      deploy:
        replicas: 1
  
  auth:
    image: sandeep1405/pythonapp:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
      depends_on:
        - db
  
  book:
    image: sandeep1405/pythonapp:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
      depends_on:
        - db
  
  borrow:
    image: sandeep1405/pythonapp:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 2
      depends_on:
        - db

  app:
    image: sandeep1405/pythonapp:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      depends_on:
        - auth
        - book
        - borrow
